// Builds the map datasets in site/assets/data/geo/ from Natural Earth (public domain).
//   node tools/build-geo.mjs            (downloads into .cache/geo on first run)
// Output is committed; rerun only when changing what the maps contain.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = process.env.GEO_CACHE || join(root, '.cache/geo');
const OUT = join(root, 'site/assets/data/geo');
const BASE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson';
mkdirSync(CACHE, { recursive: true }); mkdirSync(OUT, { recursive: true });

async function get(name) {
  const file = join(CACHE, `${name}.geojson`);
  if (!existsSync(file)) {
    console.log('downloading', name);
    const res = await fetch(`${BASE}/${name}.geojson`);
    if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
  }
  return JSON.parse(readFileSync(file, 'utf8'));
}

// ---------- geometry helpers ----------
const CENTRAL = [-2, 43, 24, 58];       // Germany + neighbours, fine detail
const EUROPE = [-25, 14, 66, 72];       // Europe, Mediterranean, Near East, medium detail

function rdp(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  const t2 = tol * tol;
  while (stack.length) {
    const [a, b] = stack.pop();
    let max = 0, idx = -1;
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, len2 = dx * dx + dy * dy;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i];
      let d2;
      if (len2 === 0) d2 = (px - ax) ** 2 + (py - ay) ** 2;
      else { const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len2)); d2 = (px - ax - t * dx) ** 2 + (py - ay - t * dy) ** 2; }
      if (d2 > max) { max = d2; idx = i; }
    }
    if (max > t2) { keep[idx] = 1; stack.push([a, idx], [idx, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}

function clipRing(ring, [x0, y0, x1, y1]) {
  // Sutherland–Hodgman against an axis-aligned rectangle.
  const edges = [
    [p => p[0] >= x0, (a, b) => [x0, a[1] + (b[1] - a[1]) * (x0 - a[0]) / (b[0] - a[0])]],
    [p => p[0] <= x1, (a, b) => [x1, a[1] + (b[1] - a[1]) * (x1 - a[0]) / (b[0] - a[0])]],
    [p => p[1] >= y0, (a, b) => [a[0] + (b[0] - a[0]) * (y0 - a[1]) / (b[1] - a[1]), y0]],
    [p => p[1] <= y1, (a, b) => [a[0] + (b[0] - a[0]) * (y1 - a[1]) / (b[1] - a[1]), y1]],
  ];
  let out = ring;
  for (const [inside, cross] of edges) {
    const inp = out; out = [];
    for (let i = 0; i < inp.length; i++) {
      const cur = inp[i], prev = inp[(i + inp.length - 1) % inp.length];
      if (inside(cur)) { if (!inside(prev)) out.push(cross(prev, cur)); out.push(cur); }
      else if (inside(prev)) out.push(cross(prev, cur));
    }
    if (!out.length) return [];
  }
  return out;
}

function clipLine(line, [x0, y0, x1, y1]) {
  // Split into runs of points inside the (slightly padded) box; good enough for rivers.
  const pad = 0.5, runs = []; let cur = [];
  for (const p of line) {
    if (p[0] >= x0 - pad && p[0] <= x1 + pad && p[1] >= y0 - pad && p[1] <= y1 + pad) cur.push(p);
    else { if (cur.length > 1) runs.push(cur); cur = []; }
  }
  if (cur.length > 1) runs.push(cur);
  return runs;
}

const r2 = n => Math.round(n * 100) / 100;
const flat = pts => { const o = []; let lx, ly; for (const [x, y] of pts) { const a = r2(x), b = r2(y); if (a === lx && b === ly) continue; o.push(a, b); lx = a; ly = b; } return o; };
const bboxHit = (pts, [x0, y0, x1, y1]) => pts.some(([x, y]) => x >= x0 && x <= x1 && y >= y0 && y <= y1);
const ringArea = r => { let s = 0; for (let i = 0; i < r.length; i++) { const [a, b] = r[i], [c, d] = r[(i + 1) % r.length]; s += a * d - c * b; } return Math.abs(s / 2); };

function polys(geom) { return geom.type === 'Polygon' ? [geom.coordinates] : geom.type === 'MultiPolygon' ? geom.coordinates : []; }

function buildPolys(geom, tol, clip, minArea) {
  const out = [];
  for (const poly of polys(geom)) {
    const rings = [];
    poly.forEach((ring, i) => {
      let r = clip ? clipRing(ring, clip) : ring;
      if (r.length < 4) return;
      r = rdp(r, tol);
      if (r.length < 4 || ringArea(r) < minArea) return;
      rings.push(flat(r));
    });
    if (rings.length && poly[0] && (!clip || bboxHit(poly[0], clip))) out.push(rings);
  }
  return out;
}

const write = (name, data) => {
  const body = `// Generated by tools/build-geo.mjs from Natural Earth (public domain). Do not edit.\nexport default ${JSON.stringify(data)};\n`;
  writeFileSync(join(OUT, name), body);
  console.log(name.padEnd(14), (body.length / 1024).toFixed(0).padStart(5), 'KB');
};

// ---------- names ----------
const RIVER_DE = { Danube: 'Donau', Rhine: 'Rhein', Rhin: 'Rhein', Vistula: 'Weichsel', Tevere: 'Tiber', Tejo: 'Tajo', Volga: 'Wolga', Dnipro: 'Dnepr', Dnepre: 'Dnepr', Neman: 'Memel', Daugava: 'Düna', Dniester: 'Dnister', Sava: 'Save', Tisa: 'Theiß', Pripyat: 'Pripjat', Thames: 'Themse', Warta: 'Warthe', Vltava: 'Moldau', Nile: 'Nil', Firat: 'Euphrat', 'Al Furat': 'Euphrat', Tigris: 'Tigris', Dicle: 'Tigris', Gange: 'Ganges', Chang: 'Jangtse', 'Chang Jiang': 'Jangtse', Yangtze: 'Jangtse', 'Huang He': 'Gelber Fluss', Zambezi: 'Sambesi', Congo: 'Kongo', Amazonas: 'Amazonas', Mississippi: 'Mississippi', Ob: 'Ob', Yenisey: 'Jenissei', Lena: 'Lena', Amur: 'Amur', Mekong: 'Mekong', Niger: 'Niger', Indus: 'Indus', Brahmaputra: 'Brahmaputra', 'Syr Darya': 'Syrdarja', 'Amu Darya': 'Amudarja', Jordan: 'Jordan', Orinoco: 'Orinoco', Paraná: 'Paraná', 'Rio de la Plata': 'Río de la Plata', 'St. Lawrence': 'Sankt-Lorenz-Strom', Colorado: 'Colorado', Missouri: 'Missouri', Ohio: 'Ohio', Mackenzie: 'Mackenzie', Yukon: 'Yukon', Murray: 'Murray', Limpopo: 'Limpopo', Orange: 'Oranje', Senegal: 'Senegal', Volta: 'Volta', Irrawaddy: 'Irawadi', Salween: 'Saluen', Hwang: 'Gelber Fluss', Xi: 'Perlfluss', Kolyma: 'Kolyma', Shannon: 'Shannon', Severn: 'Severn' };
const riverName = p => RIVER_DE[p.name] || RIVER_DE[p.name_en] || p.name_de || p.name_en || p.name;

// German → English names for English-language subjects (written to names-en.js).
const EN = { country: {}, range: {}, river: {}, lake: {}, city: {} };
const importance = sr => (sr <= 4 ? 1 : sr <= 8 ? 2 : 3);

// ---------- load ----------
const [ctr10, ctr50, states, rEu, rGl, lakesEu, lakesGl, places, regions, peaks] = await Promise.all([
  get('ne_10m_admin_0_countries'), get('ne_50m_admin_0_countries'), get('ne_10m_admin_1_states_provinces'),
  get('ne_10m_rivers_europe'), get('ne_10m_rivers_lake_centerlines'), get('ne_10m_lakes_europe'), get('ne_10m_lakes'),
  get('ne_10m_populated_places'), get('ne_10m_geography_regions_polys'), get('ne_10m_geography_regions_elevation_points'),
]);

const cname = p => p.NAME_DE || p.NAME_EN || p.NAME;
const countries = (src, tol, clip, minArea) => src.features.map(f => ({ n: (EN.country[cname(f.properties)] = f.properties.NAME_EN || f.properties.NAME, cname(f.properties)), c: f.properties.ADM0_A3, p: buildPolys(f.geometry, tol, clip, minArea) })).filter(c => c.p.length);

// ---------- cities ----------
const cityRows = places.features.map(f => {
  const p = f.properties, [lon, lat] = f.geometry.coordinates;
  const cap = /Admin-0 capital/.test(p.FEATURECLA) ? 2 : /Admin-1 capital/.test(p.FEATURECLA) ? 1 : 0;
  return { n: p.NAME_DE || p.NAME_EN || p.NAME, lon, lat, pop: p.POP_MAX || 0, cap, c: p.ADM0_A3 };
});
const inBox = (c, b) => c.lon >= b[0] && c.lon <= b[2] && c.lat >= b[1] && c.lat <= b[3];
const city = c => [c.n, r2(c.lon), r2(c.lat), Math.round(c.pop / 1000), c.cap];
places.features.forEach(f => { const p = f.properties; if (p.NAME_EN && (p.NAME_DE || p.NAME_EN) !== p.NAME_EN) EN.city[p.NAME_DE || p.NAME_EN || p.NAME] = p.NAME_EN; });
const citiesCentral = cityRows.filter(c => inBox(c, CENTRAL) && (c.pop >= 90000 || c.cap >= 1 && c.c === 'DEU' || c.cap === 2)).map(city);
const citiesEurope = cityRows.filter(c => inBox(c, EUROPE) && !inBox(c, CENTRAL) && (c.pop >= 400000 || c.cap === 2)).map(city);
const citiesWorld = cityRows.filter(c => c.cap === 2 || c.pop >= 3000000).map(city);

// ---------- lakes ----------
// The global set has the famous ones (Bodensee, Genfer See, Müritz); the Europe set adds many small ones.
const lakeName = f => { const n = f.properties.name_de || f.properties.name_en || f.properties.name || ''; if (n && f.properties.name_en && f.properties.name_en !== n) EN.lake[n] = f.properties.name_en; return n; };
const lakeOf = (f, tol, clip) => ({ n: lakeName(f), p: buildPolys(f.geometry, tol, clip, 0.0002) });
function lakes(tol, clip, glMaxRank) {
  const gl = lakesGl.features.filter(f => f.properties.scalerank <= glMaxRank);
  const names = new Set(gl.map(lakeName));
  const eu = clip ? lakesEu.features.filter(f => !names.has(lakeName(f))) : [];
  return [...gl, ...eu].map(f => lakeOf(f, tol, clip)).filter(l => l.p.length);
}
const lakesCentral = lakes(0.01, CENTRAL, 99);
const lakesEuropeLod = lakes(0.04, EUROPE, 4);
const lakesWorld = lakes(0.15, null, 1);

// ---------- rivers ----------
function rivers(tol, clip, maxImportance) {
  const out = new Map();
  const add = (props, geom, src) => {
    const name = riverName(props);
    if (!name) return;
    const en = props.name_en || props.name; if (en && en !== name) EN.river[name] ??= en;
    const imp = importance(props.scalerank);
    if (imp > maxImportance) return;
    const lines = geom.type === 'LineString' ? [geom.coordinates] : geom.coordinates;
    const key = name;
    const e = out.get(key) || { n: name, i: imp, l: [] };
    e.i = Math.min(e.i, imp);
    for (const line of lines) {
      for (const run of (clip ? clipLine(line, clip) : [line])) {
        const s = rdp(run, tol);
        if (s.length > 1) e.l.push(flat(s));
      }
    }
    if (e.l.length) out.set(key, e);
  };
  // Global centre-lines carry the big rivers; the Europe set adds the smaller named ones.
  for (const f of rGl.features) add(f.properties, f.geometry, 'g');
  const have = new Set(out.keys());
  for (const f of rEu.features) { const nm = riverName(f.properties); if (nm && !have.has(nm)) add(f.properties, f.geometry, 'e'); }
  return [...out.values()];
}
const riversCentral = rivers(0.012, CENTRAL, 3);
const riversEurope = rivers(0.05, EUROPE, 2);
const riversWorld = rivers(0.2, null, 1).filter(r => r.i === 1 || /Nil|Euphrat|Tigris|Indus|Ganges|Jangtse|Gelber|Amazonas|Mississippi|Kongo|Sambesi|Niger|Mekong|Ob|Jenissei|Lena|Amur|Wolga|Donau|Rhein|Jordan/.test(r.n));

// ---------- mountains & peaks ----------
const SKIP_RANGE = new Set(['Iberische Halbinsel', 'Kalabrien', 'Stavropol-Plateau', 'Wolgaplatte', 'Dneprhochland', 'Asowsches Hochland', 'Mittelrussische Platte']);
const ranges = regions.features
  .filter(f => f.properties.FEATURECLA === 'Range/mtn' && f.geometry && bboxHit(polys(f.geometry).flat(2), EUROPE) && !SKIP_RANGE.has(f.properties.NAME_DE))
  .map(f => ({ n: f.properties.NAME_DE || f.properties.NAME_EN || f.properties.NAME, p: buildPolys(f.geometry, 0.04, EUROPE, 0.05) })).filter(r => r.p.length);
const PEAK_DE = { Grossglockner: 'Großglockner', 'Mount Olympus': 'Olymp', Olympus: 'Olymp', Vesuvio: 'Vesuv', 'Monte Etna': 'Ätna', Galdhpiggen: 'Galdhøpiggen', 'Gora Elbrus': 'Elbrus', 'Mount Ararat': 'Ararat', 'Mont Blanc': 'Mont Blanc', Gerlach: 'Gerlachspitze', Beerenberg: 'Beerenberg' };
const peaksOut = peaks.features.filter(f => { const [x, y] = f.geometry.coordinates; return x >= EUROPE[0] && x <= EUROPE[2] && y >= EUROPE[1] && y <= EUROPE[3]; })
  .map(f => { const p = f.properties, n = p.name || p.NAME || ''; return [PEAK_DE[n] || n, r2(f.geometry.coordinates[0]), r2(f.geometry.coordinates[1]), Math.round(p.elevation || 0)]; })
  .filter(p => p[0] && p[3] > 300);

// ---------- German states ----------
const deStates = states.features.filter(f => f.properties.adm0_a3 === 'DEU' || f.properties.ADM0_A3 === 'DEU')
  .map(f => ({ n: f.properties.name_de || f.properties.name, p: buildPolys(f.geometry, 0.008, CENTRAL, 0.0001) }));

// ---------- write ----------
const rangesCentral = regions.features
  .filter(f => f.properties.FEATURECLA === 'Range/mtn' && f.geometry && bboxHit(polys(f.geometry).flat(2), CENTRAL) && !SKIP_RANGE.has(f.properties.NAME_DE))
  .map(f => ({ n: f.properties.NAME_DE || f.properties.NAME_EN || f.properties.NAME, p: buildPolys(f.geometry, 0.02, CENTRAL, 0.02) })).filter(r => r.p.length);
const peaksCentral = peaksOut.filter(p => p[1] >= CENTRAL[0] && p[1] <= CENTRAL[2] && p[2] >= CENTRAL[1] && p[2] <= CENTRAL[3] && p[3] > 400);
write('central.js', { bbox: CENTRAL, countries: countries(ctr10, 0.008, CENTRAL, 0.0002), states: deStates, rivers: riversCentral, lakes: lakesCentral, cities: citiesCentral, mountains: rangesCentral, peaks: peaksCentral });
write('europe.js', { bbox: EUROPE, countries: countries(ctr10, 0.04, EUROPE, 0.01), rivers: riversEurope, lakes: lakesEuropeLod, cities: [...citiesCentral.filter(c => c[3] >= 400 || c[4] === 2), ...citiesEurope], mountains: ranges, peaks: peaksOut });
write('world.js', { countries: countries(ctr50, 0.1, null, 0.05), rivers: riversWorld, lakes: lakesWorld, cities: citiesWorld });

// Catalogue the validator and authors use to check names.
const catalog = {
  rivers: [...new Set([...riversCentral, ...riversEurope, ...riversWorld].map(r => r.n))].sort((a, b) => a.localeCompare(b, 'de')),
  countries: [...new Set(ctr10.features.map(f => cname(f.properties)))].sort((a, b) => a.localeCompare(b, 'de')),
  states: deStates.map(s => s.n).sort((a, b) => a.localeCompare(b, 'de')),
  ranges: ranges.map(r => r.n).sort((a, b) => a.localeCompare(b, 'de')),
  peaks: peaksOut.map(p => p[0]).sort((a, b) => a.localeCompare(b, 'de')),
  lakes: [...new Set([...lakesCentral, ...lakesEuropeLod, ...lakesWorld].map(l => l.n).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'de')),
};
write('catalog.js', catalog);
for (const f of regions.features) if (f.properties.FEATURECLA === 'Range/mtn' && f.properties.NAME_DE && f.properties.NAME_EN && f.properties.NAME_DE !== f.properties.NAME_EN) EN.range[f.properties.NAME_DE] = f.properties.NAME_EN;
for (const k of Object.keys(EN)) for (const [de, en] of Object.entries(EN[k])) if (de === en) delete EN[k][de];
write('names-en.js', EN);
writeFileSync(join(OUT, 'CATALOG.txt'), Object.entries(catalog).map(([k, v]) => `## ${k} (${v.length})\n${v.join(', ')}\n`).join('\n'));
console.log('rivers central/europe/world:', riversCentral.length, riversEurope.length, riversWorld.length);
