// Seeds the gazetteer site/assets/data/geo/places.js (places + landscapes) with coordinates from Wikipedia.
//   node tools/build-places.mjs
// Entry: 'Display name' or ['Display name', 'Wikipedia title', kind]; kind: place (default) | land (landscape label) | site

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { geocode } from './lib/wiki-geo.mjs';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'site/assets/data/geo/places.js');

const PLACES = [
  // Germany
  ['Kalkriese', 'Museum und Park Kalkriese', 'site'], 'Xanten', 'Trier', 'Köln', 'Mainz', 'Worms', 'Speyer', 'Aachen', ['Ingelheim', 'Ingelheim am Rhein'], 'Lorsch', 'Fulda', 'Regensburg', 'Augsburg', 'Bonn', 'Koblenz', 'Remagen', 'Neuss',
  ['Wittenberg', 'Lutherstadt Wittenberg'], ['Eisleben', 'Lutherstadt Eisleben'], 'Erfurt', 'Eisenach', ['Wartburg', 'Wartburg', 'site'], 'Weimar', 'Jena', 'Leipzig', 'Dresden', 'Potsdam', 'Berlin', 'Magdeburg', 'Quedlinburg', 'Hildesheim',
  'Hamburg', 'Lübeck', 'Bremen', 'Münster', 'Osnabrück', 'Hannover', 'Braunschweig', 'Göttingen', 'Kassel', 'Frankfurt am Main', 'Heidelberg', 'Stuttgart', 'Tübingen', 'Ulm', 'Konstanz', 'Freiburg im Breisgau', 'München', 'Nürnberg', 'Bamberg', 'Würzburg', 'Bayreuth',
  'Rostock', 'Stralsund', 'Schwerin', 'Kiel', 'Flensburg', 'Dessau-Roßlau', 'Halle (Saale)', 'Gotha', 'Naumburg (Saale)', 'Meißen', 'Görlitz', 'Cottbus', 'Frankfurt (Oder)', 'Chemnitz', 'Düsseldorf', 'Dortmund', 'Essen', 'Duisburg', 'Karlsruhe', 'Mannheim', 'Saarbrücken', 'Wiesbaden', 'Darmstadt', 'Passau', 'Ingolstadt', 'Kempten (Allgäu)', 'Lindau (Bodensee)', 'Friedrichshafen', 'Oldenburg (Oldb)', 'Emden', 'Wilhelmshaven', 'Cuxhaven', 'Bremerhaven', 'Greifswald', 'Wismar', 'Wolfsburg', 'Salzgitter', 'Zwickau', 'Plauen', 'Gera', 'Suhl', 'Coburg',
  ['Peenemünde', 'Peenemünde', 'site'], ['KZ Dachau', 'KZ Dachau', 'site'], ['KZ Buchenwald', 'KZ Buchenwald', 'site'], ['KZ Bergen-Belsen', 'KZ Bergen-Belsen', 'site'], ['KZ Sachsenhausen', 'KZ Sachsenhausen', 'site'], ['KZ Flossenbürg', 'KZ Flossenbürg', 'site'], ['KZ Neuengamme', 'KZ Neuengamme', 'site'], ['KZ Ravensbrück', 'KZ Ravensbrück', 'site'], ['Hambacher Schloss', 'Hambacher Schloss', 'site'], ['Schloss Neuschwanstein', 'Schloss Neuschwanstein', 'site'], ['Burg Hohenzollern', 'Burg Hohenzollern', 'site'], ['Reichsparteitagsgelände', 'Reichsparteitagsgelände', 'site'], ['Wannsee', 'Großer Wannsee', 'site'], ['Kölner Dom', 'Kölner Dom', 'site'], ['Brandenburger Tor', 'Brandenburger Tor', 'site'], ['Paulskirche', 'Paulskirche (Frankfurt am Main)', 'site'], ['Bonn (Bundeshauptstadt)', 'Bonn'], ['Bückeburg', 'Bückeburg'], ['Bayreuther Festspielhaus', 'Richard-Wagner-Festspielhaus', 'site'], ['Zeche Zollverein', 'Zeche Zollverein', 'site'], ['Externsteine', 'Externsteine', 'site'], ['Heidenheim an der Brenz', 'Heidenheim an der Brenz'],
  // Rhine & Roman
  ['Straßburg', 'Straßburg'], 'Basel', 'Rotterdam', 'Köln-Deutz', ['Colonia Claudia Ara Agrippinensium', 'Köln'], ['Mogontiacum', 'Mainz'], ['Augusta Treverorum', 'Trier'], ['Castra Regina', 'Regensburg'], ['Augusta Vindelicorum', 'Augsburg'], ['Carnuntum', 'Petronell-Carnuntum'], 'Vindobona', 'Aquincum', 'Londinium', 'Eboracum', ['Lugdunum', 'Lyon'], 'Colchester',
  ['Hadrianswall', 'Hadrianswall', 'site'], ['Saalburg', 'Römerkastell Saalburg', 'site'], ['Schlacht am Harzhorn', 'Harzhornereignis', 'site'],
  // Antiquity & Mediterranean
  'Rom', 'Athen', 'Sparta', 'Troja', 'Karthago', 'Alexandria', 'Memphis (Ägypten)', 'Theben (Ägypten)', 'Babylon', 'Ninive', ['Ur', 'Ur (Stadt)'], 'Jerusalem', 'Konstantinopel', 'Mekka', 'Medina', 'Delphi', ['Olympia', 'Olympia (Griechenland)'], 'Marathon (Griechenland)', 'Thermopylen', 'Pompeji', 'Ravenna', 'Tours', 'Poitiers', 'Cannae', 'Syrakus', 'Korinth', 'Ephesos', 'Persepolis', 'Gizeh', 'Assuan', 'Uruk', 'Knossos', 'Mykene', 'Pergamon', 'Damaskus', 'Bagdad', 'Samarkand', 'Córdoba (Spanien)', 'Granada', 'Toledo', 'Venedig', 'Florenz', 'Mailand', 'Genua', 'Neapel', 'Palermo', ['Canossa', 'Canossa (Gemeinde)'], 'Avignon', ['Byzanz', 'Istanbul'], 'Antiochia am Orontes', 'Edessa (Mesopotamien)', 'Akkon', 'Mailand',
  // Europe
  'Paris', 'Versailles', 'Reims', 'Lyon', 'Marseille', 'Straßburg', 'Orléans', 'Compiègne', 'London', 'Dublin', 'Edinburgh', 'Wien', 'Prag', 'Budapest', 'Warschau', 'Krakau', 'Danzig', 'Breslau', ['Königsberg', 'Kaliningrad'], 'Riga', 'Tallinn', 'Stockholm', 'Oslo', 'Kopenhagen', 'Helsinki', 'Moskau', ['Sankt Petersburg', 'Sankt Petersburg (Stadt)'], 'Kiew', 'Minsk', 'Bukarest', 'Sofia', 'Belgrad', 'Sarajevo', 'Zagreb', 'Ljubljana', 'Bern', 'Zürich', 'Genf', 'Brüssel', 'Amsterdam', 'Den Haag', 'Luxemburg (Stadt)', 'Madrid', 'Barcelona', 'Sevilla', 'Lissabon', 'Waterloo (Belgien)', 'Sedan', 'Verdun', 'Tannenberg (Ostpreußen)', 'Ypern', 'Somme', 'Stalingrad', 'Leningrad', 'Dünkirchen', 'Rotterdam', 'Coventry', ['Guernica', 'Gernika-Lumo'], 'Auschwitz', 'Treblinka', 'Sobibor', 'Majdanek', 'Chełmno nad Nerem', 'Bełżec', ['Theresienstadt', 'Terezín'], 'Mauthausen', 'Jalta', 'Potsdam', 'Canterbury', 'Oxford', 'Cambridge', 'Athos', 'Santiago de Compostela', 'Lourdes', 'Fátima', ['Vatikanstadt', 'Vatikanstadt'], 'Straßburg', 'Maastricht', 'Schengen', 'Brüssel',
  ['Kreta', 'Kreta', 'land'], ['Sizilien', 'Sizilien', 'land'], ['Sardinien', 'Sardinien', 'land'], ['Korsika', 'Korsika', 'land'], ['Zypern', 'Zypern', 'land'], ['Peloponnes', 'Peloponnes', 'land'], ['Anatolien', 'Anatolien', 'land'], ['Balearen', 'Balearen', 'land'], ['Island', 'Island', 'land'], ['Britannien', 'Great Britain', 'land'], ['Gallien', 'Frankreich', 'land'], ['Mesopotamien', 'Mesopotamien', 'land'], ['Levante', 'Levante', 'land'], ['Sinai', 'Sinai-Halbinsel', 'land'], ['Iberische Halbinsel', 'Iberische Halbinsel', 'land'], ['Balkan', 'Balkanhalbinsel', 'land'], ['Skandinavien', 'Skandinavien', 'land'],
  // World
  'Peking', 'Tokio', 'Delhi', 'Kairo', 'Washington, D.C.', 'New York City', 'Philadelphia', 'Boston', 'Jamestown (Virginia)', 'Yorktown (Virginia)', 'Havanna', 'Hanoi', 'Ho-Chi-Minh-Stadt', 'Seoul', 'Pjöngjang', 'Panmunjeom', 'Hiroshima', 'Nagasaki', 'Pearl Harbor', ['Sueskanal', 'Sueskanal'], 'Panamakanal', 'Gibraltar', 'Bosporus', 'Dardanellen', 'Kap der Guten Hoffnung', 'Kap Hoorn', 'San Salvador (Bahamas)', 'Mexiko-Stadt', 'Cusco', 'Cajamarca', 'Kalkutta', 'Goa', 'Malakka', 'Macau', 'Nagasaki', 'Lima', 'Rio de Janeiro', 'Buenos Aires', 'Kapstadt', 'Johannesburg', 'Nairobi', 'Lagos', 'Timbuktu', 'Sankt Petersburg', 'Wladiwostok', 'Mumbai', 'Peking', 'Shanghai', 'Hongkong', 'Singapur', 'Sydney', 'Jakarta', 'Teheran', 'Riad', 'Bagdad', 'Istanbul', 'Ankara', 'Tel Aviv-Jaffa', 'Gaza (Stadt)', 'Kabul', 'Islamabad', 'Dhaka', 'Bangkok', 'Manila', 'Kuba', 'Bikini-Atoll', ['Tschernobyl', 'Kernkraftwerk Tschernobyl'], ['Fukushima', 'Kernkraftwerk Fukushima Daiichi'], ['Cape Canaveral', 'Cape Canaveral Space Force Station'], 'Baikonur', ['Wostotschny', 'Kosmodrom Wostotschny'], 'Kourou',
  ['Mekka (Kaaba)', 'Kaaba', 'site'], ['Bodh Gaya', 'Bodhgaya', 'site'], ['Lumbini', 'Lumbini', 'site'], ['Varanasi', 'Varanasi', 'site'], ['Bethlehem', 'Bethlehem', 'site'], ['Nazaret', 'Nazaret', 'site'], ['Rom (Petersdom)', 'Petersdom', 'site'], ['Sinai (Berg)', 'Dschabal Musa', 'site'], ['Stonehenge', 'Stonehenge', 'site'], ['Akropolis', 'Akropolis (Athen)', 'site'], ['Pyramiden von Gizeh', 'Pyramiden von Gizeh', 'site'], ['Kolosseum', 'Kolosseum', 'site'], ['Pantheon', 'Pantheon (Rom)', 'site'], ['Notre-Dame de Paris', 'Notre-Dame de Paris', 'site'], ['Sagrada Família', 'Sagrada Família', 'site'], ['Louvre', 'Louvre', 'site'], ['Prado', 'Museo del Prado', 'site'], ['Uffizien', 'Uffizien', 'site'], ['Kunsthistorisches Museum', 'Kunsthistorisches Museum', 'site'], ['Alhambra', 'Alhambra', 'site'], ['Taj Mahal', 'Taj Mahal', 'site'], ['Machu Picchu', 'Machu Picchu', 'site'], ['Chichén Itzá', 'Chichén Itzá', 'site'], ['Angkor Wat', 'Angkor Wat', 'site'], ['Große Mauer', 'Chinesische Mauer', 'site'], ['Tempel von Karnak', 'Tempel von Karnak', 'site'],
  // Landscapes (labels only)
  ['Schwarzwald', 'Schwarzwald', 'land'], ['Eifel', 'Eifel', 'land'], ['Hunsrück', 'Hunsrück', 'land'], ['Taunus', 'Taunus', 'land'], ['Westerwald', 'Westerwald', 'land'], ['Spessart', 'Spessart', 'land'], ['Rhön', 'Rhön', 'land'], ['Thüringer Wald', 'Thüringer Wald', 'land'], ['Odenwald', 'Odenwald', 'land'], ['Schwäbische Alb', 'Schwäbische Alb', 'land'], ['Bayerischer Wald', 'Bayerischer Wald', 'land'], ['Fichtelgebirge', 'Fichtelgebirge', 'land'], ['Pfälzerwald', 'Pfälzerwald', 'land'], ['Sauerland', 'Sauerland', 'land'], ['Rothaargebirge', 'Rothaargebirge', 'land'], ['Teutoburger Wald', 'Teutoburger Wald', 'land'], ['Lüneburger Heide', 'Lüneburger Heide', 'land'], ['Allgäu', 'Allgäu', 'land'], ['Elbsandsteingebirge', 'Elbsandsteingebirge', 'land'], ['Fränkische Alb', 'Fränkische Alb', 'land'], ['Wattenmeer', 'Wattenmeer (Nordsee)', 'land'], ['Ruhrgebiet', 'Ruhrgebiet', 'land'], ['Oberrheingraben', 'Oberrheingraben', 'land'], ['Norddeutsche Tiefebene', 'Norddeutsches Tiefland', 'land'], ['Alpenvorland', 'Alpenvorland', 'land'], ['Mecklenburgische Seenplatte', 'Mecklenburgische Seenplatte', 'land'], ['Spreewald', 'Spreewald', 'land'], ['Lausitz', 'Lausitz', 'land'], ['Vogtland', 'Vogtland', 'land'], ['Rügen', 'Rügen', 'land'], ['Sylt', 'Sylt', 'land'], ['Usedom', 'Usedom', 'land'], ['Fehmarn', 'Fehmarn', 'land'], ['Helgoland', 'Helgoland', 'land'], ['Kaiserstuhl', 'Kaiserstuhl (Gebirge)', 'land'], ['Loreley', 'Loreley', 'site'], ['Mittelrheintal', 'Oberes Mittelrheintal', 'land'], ['Münsterland', 'Münsterland', 'land'], ['Niederrhein', 'Niederrhein', 'land'], ['Rheinhessen', 'Rheinhessen', 'land'], ['Pfalz', 'Pfalz (Region)', 'land'], ['Franken', 'Franken (Region)', 'land'], ['Schwaben', 'Schwaben (Region)', 'land'], ['Oberlausitz', 'Oberlausitz', 'land'], ['Altmark', 'Altmark', 'land'], ['Uckermark', 'Uckermark', 'land'], ['Harz', 'Harz', 'land'], ['Erzgebirge', 'Erzgebirge', 'land'], ['Hegau', 'Hegau', 'land'], ['Oberschwaben', 'Oberschwaben', 'land'],
];

// Region names whose Wikipedia article has no coordinates: approximate label positions [lon, lat].
const MANUAL = [['Canossa', 10.45, 44.585, 'site'], ['Sankt Petersburg', 30.316, 59.939, 'place'], ['Levante', 36.0, 34.5, 'land'], ['Skandinavien', 15.0, 63.0, 'land'], ['Sinai (Berg)', 33.975, 28.539, 'site'], ['Große Mauer', 116.02, 40.359, 'site'], ['Tempel von Karnak', 32.657, 25.719, 'site'], ['Wattenmeer', 8.3, 53.9, 'land'], ['Alpenvorland', 11.5, 47.9, 'land'], ['Kaiserstuhl', 7.65, 48.1, 'land'], ['Mittelrheintal', 7.7, 50.2, 'land'], ['Niederrhein', 6.55, 51.55, 'land'], ['Rheinhessen', 8.1, 49.8, 'land'], ['Pfalz', 8.0, 49.35, 'land'], ['Schwaben', 10.0, 48.3, 'land'], ['Uckermark', 13.85, 53.15, 'land']];

const entries = PLACES.map(e => typeof e === 'string' ? { n: e, w: e, k: 'place' } : { n: e[0], w: e[1] || e[0], k: e[2] || 'place' });
const titles = [...new Set(entries.map(e => e.w))];
const found = await geocode(titles, 'de');
const missing = titles.filter(t => !found[t]);
Object.assign(found, await geocode(missing, 'en'));
const out = [], seen = new Set();
for (const e of entries) {
  const g = found[e.w];
  if (!g) { console.log('✗ no coordinates:', e.n, `(${e.w})`); continue; }
  if (seen.has(e.n)) continue; seen.add(e.n);
  out.push([e.n.replace(/ \(.*\)$/, '').replace(/, D\.C\.$/, ', D.C.'), Math.round(g.lon * 1000) / 1000, Math.round(g.lat * 1000) / 1000, e.k]);
}
for (const [n, lon, lat, k] of MANUAL) if (!seen.has(n)) { seen.add(n); out.push([n, lon, lat, k]); }
writeFileSync(OUT, `// Gazetteer: [name, lon, lat, kind]; generated by tools/build-places.mjs from Wikipedia coordinates.\n// kind: place | site | land (landscape label)\nexport default ${JSON.stringify(out)};\n`);
console.log(out.length, 'places written');
